
import { Injectable } from "@angular/core";
import { PermissionService } from "src/app/core/service/permission.service";
import { RouteInfo } from "./sidebar.metadata";
@Injectable({
  providedIn: "root",
})
export class AllRoutesService {
  constructor(public permissionService: PermissionService) { }
  ROUTES: RouteInfo[] = [
    {
      path: "",
      title: "MENUITEMS.MAIN.TEXT",
      moduleName: "",
      iconType: "",
      icon: "",
      class: "",
      groupTitle: true,
      badge: "",
      badgeClass: "",
      role: ["All"],
      displayPermission: true,
      submenu: [],
    },
    {
      path: "",
      title: "MENUITEMS.ROLES.TEXT",
      moduleName: "role",
      iconType: "material-icons-two-tone",
      icon: "lock_person",
      class: "menu-toggle",
      groupTitle: false,
      badge: "",
      badgeClass: "",
      role: ["All"],
      displayPermission: true,
      submenu: [
        {
          path: "/admin/role/allroles",
          title: "MENUITEMS.ROLES.LIST.ALL-ROLES",
          moduleName: "role",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          displayPermission: true,
          submenu: [],
        },
        {
          path: "/admin/role/addrole",
          title: "MENUITEMS.ROLES.LIST.NEW-ROLE",
          moduleName: "role",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          displayPermission: true,
          submenu: [],
        }
      ],
    },
    {
      path: "",
      title: "MENUITEMS.USERS.TEXT",
      moduleName: "user",
      iconType: "material-icons-two-tone",
      icon: "person",
      class: "menu-toggle",
      groupTitle: false,
      badge: "",
      badgeClass: "",
      role: ["All"],
      displayPermission: true,
      submenu: [
        {
          path: "/admin/user/allusers",
          title: "MENUITEMS.USERS.LIST.All-USERS",
          moduleName: "user",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          displayPermission: true,
          submenu: [],
        },
        {
          path: "/admin/user/adduser",
          title: "MENUITEMS.USERS.LIST.NewUser",
          moduleName: "user",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          displayPermission: true,
          submenu: [],
        }
      ],
    },
    {
      path: "",
      title: "MENUITEMS.productdepartment.TEXT",
      moduleName: "productdepartment",
      iconType: "material-icons-two-tone",
      icon: "person",
      class: "menu-toggle",
      groupTitle: false,
      badge: "",
      badgeClass: "",
      role: ["All"],
      displayPermission: true,
      submenu: [
        {
          path: "/admin/productdepartment/allproductsdepartment",
          title: "MENUITEMS.productsdepartment.LIST.All-productsdepartment",
          moduleName: "productdepartment",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          displayPermission: true,
          submenu: [],
        },
        {
          path: "/admin/productdepartment/addproductdepartment",
          title: "MENUITEMS.productsdepartment.LIST.Newproductdepartment",
          moduleName: "productdepartment",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          displayPermission: true,
          submenu: [],
        }
      ],
    }
    // Admin Modules
  ];
}
